trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - '*'

variables:
  configuration: Release

jobs:
  - job: linux
    pool:
      vmImage: ubuntu-16.04
    workspace:
      clean: all

    steps:
      - task: NodeTool@0
        displayName: Node install
        inputs:
          versionSpec: '10.16.0'

      - bash: node --version && yarn --version && dotnet --info
        displayName: Print versions

      - bash: ./build.sh setup
        displayName: Install dependencies

      - bash: ./build.sh compile
        displayName: Initial build

      - bash: ./build.sh lint
        displayName: Lint

      - bash: ./build.sh test
        displayName: Unit tests

      - task: PublishTestResults@2
        displayName: Publish unit test results
        condition: always()
        inputs:
          testRunTitle: linux
          testResultsFormat: VSTest
          testResultsFiles: artifacts/TestResults/*.trx

      - bash: ./build.sh
        displayName: Package cli application

      - bash: ./build.sh install
        displayName: Install cli application

  - job: macOS
    pool:
      vmImage: macOS-10.14
    workspace:
      clean: all

    steps:
      - task: NodeTool@0
        displayName: Node install
        inputs:
          versionSpec: '10.16.0'

      - bash: node --version && yarn --version && dotnet --info
        displayName: Print versions

      - bash: ./build.sh setup
        displayName: Install dependencies

      - bash: ./build.sh compile
        displayName: Initial build

      - bash: ./build.sh lint
        displayName: Lint

      - bash: ./build.sh test
        displayName: Unit tests

      - task: PublishTestResults@2
        displayName: Publish unit test results
        condition: always()
        inputs:
          testRunTitle: macOS
          testResultsFormat: VSTest
          testResultsFiles: artifacts/TestResults/*.trx

      - bash: ./build.sh
        displayName: Package cli application

      - bash: ./build.sh install
        displayName: Install cli application
