version: '3.7'
services:
  webtty:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    command: 'make setup dev-docker'
    volumes:
      - .:/app
      - /app/src/WebTty.Hosting/Client/node_modules
      - /app/.build
    ports:
      - "3000:3000"
      - "5000:5000"
