version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/src/WebTty.Hosting/Client"
    update_schedule: "weekly"

  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "weekly"

  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
